import type { Metadata } from 'next';
import './globals.css';
import SideNav from './_components/SideNav/SideNav';
import TopNav from './_components/TopNav/TopNav';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <SideNav />
        <div className='shell__body'>
          <TopNav
            name='Samantha Villanueva'
            avatarIconSrc='/images/worm_with_glasses.png'
          />
          {children}
        </div>
      </body>
    </html>
  );
}
